openapi: 3.0.0
info:
  description: Schema
  version: 1.0.0
  title: Schema with various data
paths:
  /contexts/traceability-v1.jsonld:
    get:
      tags:
        - Contexts
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/schemas/common/Context.yml'
  /schemas/common/Brand.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Brand.yml'
  /schemas/common/Organization.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Organization.yml'
  /schemas/common/Entity.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Entity.yml'
