openapi: 3.0.0
info:
  title: Traceability Schemas
  version: 1.0.0
servers:
  # - url: http://localhost:5000
  - url: http://localhost:5000/openapi/components
  - url: https://w3id.org/traceability/api

paths:
  /schemas/common/Brand.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Brand.yml'

  /schemas/common/Entity.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Entity.yml'

  /schemas/common/Organization.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Organization.yml'

  /schemas/common/Person.yml:
    get:
      tags:
        - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './components/schemas/common/Person.yml'
