$linkedData:
  term: Package
  '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#Package
title: Package
description: >-
  Any self-contained wrapping or container within which goods can be contained,
  such as a box or a barrel which can be filled, partially filled or empty.
type: object
required: []
properties:
  type:
    oneOf:
      - type: array
      - type: string
        enum:
          - Package
  physicalShippingMarks:
    title: shippingMarks
    description: >-
      The identifying details of a package or the actual markings that appear on
      the package(s). This information is provided by the shipper.
    type: string
    $linkedData:
      term: shippingMarks
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#physicalShippingMarks
  quantity:
    title: Quantity
    description: The quantity of the product contained by a package.
    type: number
    $linkedData:
      term: quantity
      '@id': https://www.gs1.org/voc/netContent
  packagingType:
    title: Packaging Type
    description: Links to details about packaging material type, quantity, and thickness
    type: string
    $linkedData:
      term: packagingType
      '@id': https://www.gs1.org/voc/packagingMaterial
  netWeight:
    title: A measure of the net weight (mass).
    type: number
    $linkedData:
      term: weight
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#netWeightMeasure
  grossWeight:
    title: >-
      A measure of the gross weight (mass) which includes packaging but excludes
      any transport equipment.
    type: number
    $linkedData:
      term: weight
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#grossWeightMeasure
  weightUnit:
    title: Weight Unit
    description: The unit of measure which can be expressed in imperial or metric terms
    type: string
    $linkedData:
      term: weightUnit
      '@id': https://schema.org/unitCode
  height:
    title: Height of the product
    type: string
    $linkedData:
      term: height
      '@id': https://schema.org/height
  width:
    title: Width of the product
    type: string
    $linkedData:
      term: width
      '@id': https://schema.org/width
  depth:
    title: Depth of the Product
    type: string
    $linkedData:
      term: depth
      '@id': https://schema.org/depth
  grossVolume:
    title: Volume
    description: >-
      Calculated by multiplying the width, height, and length of the packed
      cargo.
    type: number
    $linkedData:
      term: volume
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#grossVolumeMeasure
  volumeUnit:
    title: Volume Unit
    description: >-
      The unit of measure which can be expressed in either imperial or metric
      terms
    type: string
    $linkedData:
      term: volumeUnit
      '@id': https://schema.org/unitCode
example: |-
  {
    "type": [
      "Package"
    ],
    "physicalShippingMarks": "1 of 3",
    "quantity": 10, 
    "packagingType": "Box",
    "grossWeight": 75,
    "grossWeightUnit": "lbs",
    "grossVolume": 8,
    "grossVolumeUnit": "sqf"
  }
