$linkedData:
  term: SIMASteelImportLicense
  '@id': https://w3id.org/traceability#SIMASteelImportLicense
title: SIMA Steel Import License
description: SIMA Steel Import License
type: object
properties:
  type:
    oneOf:
      - type: array
      - type: string
        enum:
          - SIMASteelImportLicense
  applicantCompany:
    title: Applicant Company
    description: Company responsible for shipment
    $ref: ./Organization.yml
    $linkedData:
      term: applicantCompany
      '@id': https://schema.org/Organization
  customsEntryNumber:
    title: Customs Entry Number
    description: Input if known at time of application. This numberis optional.
    type: string
    $linkedData:
      term: customsEntryNumber
      '@id': https://schema.org/identifier
  importer:
    title: Importer
    description: Name of Importer of Record.
    $ref: ./Organization.yml
    $linkedData:
      term: importer
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#importerParty
  exporter:
    title: Exporter
    description: Name of Exporter.
    $ref: ./Organization.yml
    $linkedData:
      term: exporter
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#exporterParty
  manufacturer:
    title: Manufacturer
    description: Name of manufacturer(s) of the product(s) or shipper(s). May list multiple
manufacturers or as unknown.
    type: array
    items:
      $ref: ./Organization.yml
    $linkedData:
      term: manufacturer
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#manufacturerParty  
  countryOfOrigin:
    title: Country of Origin
    description: Country in which the product(s) were manufactured. The two-letter ISO 3166-1 alpha-2 country code.
    type: string
    $linkedData:
      term: countryOfOrigin
      '@id': https://schema.org/addressCountry
  countryOfExportation:
    title: Country of Exportation
    description: Country of Exportation: Country from which the product(s) were exported. The two-letter ISO 3166-1 alpha-2 country code.
    type: string
    $linkedData:
      term: countryOfExportation
      '@id': https://schema.org/addressCountry
  expectedPortOfEntry: 
    title: Expected Port of Entry
    description: Expected port of entry. 
    type: string
    $linkedData:
      term: expectedPortOfEntry
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#UNECELOCODE
  expectedDateOfExport: 
    title: Expected Date of Export
    description: Date product(s) expected to be shipped from the country of exportation.
    type: string
    $linkedData:
      term: expectedDateOfExport
      '@id': >-
        http://www.w3.org/2001/XMLSchema#dateTime
  expectedDateOfExport: 
    title: Expected Date of Export
    description: Date product(s) expected to be shipped from the country of exportation.
    type: string
    $linkedData:
      term: expectedDateOfExport
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#exportExitDateTime
      '@type': http://www.w3.org/2001/XMLSchema#dateTime
  expectedDateOfImport: 
    title: Expected Date of Import
    description: Date product(s) expected to be shipped from the country of exportation.
    type: string
    $linkedData:
      term: expectedDateOfImport
      '@id': https://w3id.org/traceability#importDateTime
      '@type': http://www.w3.org/2001/XMLSchema#dateTime

      
additionalProperties: false
example: |-
  {
    "type": "SIMASteelImportLicense",
    "billOfLadingNumber": "991205182A",
    
  }
