$linkedData:
  term: SIMASteelImportLicenseCertificate
  '@id': https://w3id.org/traceability#SIMASteelImportLicenseCertificate
title: SIMA Steel Import License Certificate
description: SIMA Steel Import Licensing Application based on https://www.trade.gov/us-industry-licensing.
type: object
properties:
  '@context':
    type: array
    const:
      - 'https://www.w3.org/2018/credentials/v1'
      - 'https://w3id.org/traceability/v1'
  type:
    type: array
    const:
      - VerifiableCredential
      - SIMASteelImportLicenseCertificate
  id:
    type: string
  name:
    type: string
  description:
    type: string
  issuanceDate:
    type: string
  issuer:
    type: object
  credentialSubject:
    type: object
  proof:
    type: object
  relatedLink:
    title: Related Link
    description: Links related to this verifiable credential
    type: array
    items:
      $ref: ./LinkRole.yml
additionalProperties: false
required: []
example: |-
  {
    "issue": "https://github.com/w3c-ccg/traceability-vocab/issues/298"
  }
