name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      # must run first to build schemas.
      - name: Build
        run: npm run build:all

      - name: Test Schemass
        run: npm run test:schemas

      # must run second to test credentials.
      - name: Test
        run: npm run test:credentials
